### ISSUE TITLE
Updating data through observables

### ISSUE THREAD

**Issue by fischerman** [dhilt/vscroll#32]
First of all, thanks for the great library! I'm trying to use ngx-ui-scroll to build a chat, i.e. showing a list of messages. Messages might change and new messages can be added at the bottom. If the user scrolls up older messages are retrieved from the server. The signature already allows the passing of an observable for data retrieval. However, that observable is not treated as a stream of data. Instead, the first value is taken and converted to a Promise. I didn't look at all the code but I think vscroll could be improved by making `FetchGetResult` an observable. 

- vscroll would keep track of all subscriptions that is has items for. It would properly unsubscribe once the range is removed from the UI. At the moment, subscriptions that are not completed by the caller are leaking because vscroll doesn't call unsubscribe after the first value was emitted. (vscroll only calls unsubscribe on completion of the observable, which is technically not required.)
- vscroll would detect changes of the items, whenever `next` is called on a subscription.
- If `get` is called and vscoll detects EOF or BOF, a new value in the observable can move those "markers" allowing to add data dynamically at a later stage.

**Comment by fischerman** [comment]
Here is an example of an updating observable: 
```
datasource: IDatasource<string> = {
    get: (index: number, count: number) => {
      const data = [];
      for (let i = index; i <= index + count - 1; i++) {
        data.push('item #' + i);
      }
      return interval(1000).pipe(
        map(i => data.map(s => s + ` (${i}th interval)`)),
      )
    }
  }
```

**Comment by dhilt** [comment]
@fischerman Hello! I made stackblitz demo containing sources of ngx-ui-scroll v2.3.0 and vscroll v1.4.1: https://stackblitz.com/edit/angular-ngx-ui-scroll-and-vscroll-integration. The code that is responsible for `Datasource.get` method handling can be found at `src/vscroll/processes/fetch.ts`. The Datasource implementation can be found at `src/app/app.component.ts`. You may fork the demo and try to apply your thoughts taking into account that the vscroll has no rxjs dependencies and does not know what kind of signature of the `get` method is used before it is called. Though we could pass a parameter via `Datasource.settings` determining a new strategy of fetching... Anyway, I'd love to see your idea in a live demo, and then, if we found it appropriate, we could think on its generalization. 

From the other hand, I would also suggest to look at the problem from a different angle. You are right, observables are not streams from the vscroll's prospective. It's just another way of getting some fixed portion of data in a single run. Changing this behaviour might take too much efforts with no-guaranteed success. It's too deep in the core and the architecture design conflict might be just unresolvable. But instead, the stream logic could be implemented on the App level. Please, follow this article I posted in the ngx-ui-scroll wiki in 2020: https://github.com/dhilt/ngx-ui-scroll/wiki/Chat-App.
