### ISSUE TITLE
startIndex not working as expected

### ISSUE THREAD

**Issue by paulflo150** [dhilt/vscroll#35]
Hi,
first of all thanks for the work you put into this library!

I am having a little trouble using startIndex in combination with certain bufferSize values. For instance using the following values scrolls to index 27, instead of 34:

```
      settings: {
        bufferSize: 8,
        minIndex: 1,
        startIndex: 34,
      },
```
https://stackblitz.com/edit/angular-ngx-ui-scroll-and-vscroll-integration-ybt8zd

Settings the bufferSize high enough will make everything work as expected.

Thanks!

**Comment by dhilt** [comment]
@paulflo150 Thanks for the repro, you provided a combination of params that leads to wrong shift, so I was able to add the [falling spec](https://github.com/dhilt/ngx-ui-scroll/pull/298) in the ngx-ui-scroll repository based on it. As a workaround (I don't think it will be a long-term fix, but maybe you want to make this case work properly before it is done) I would suggest to fix scroll position after the first vscroll workflow cycle is completed. This can be done by putting the following code in constructor or ngOnInit:

```js
const {  adapter, settings: { minIndex, startIndex } } = this.datasource;
this.datasource.adapter.isLoading$
  .pipe(
    filter((v) => !v),
    take(1)
  )
  .subscribe(() =>
    adapter.fix({
      // if the item size is not constant you may parse DOM by [data-sid=startIndex] 
      // and use getBoundingClientRect() to get the position value
      scrollPosition: (startIndex - minIndex) * adapter.bufferInfo.defaultSize
    })
  );
```

**Comment by paulflo150** [comment]
Thanks, I will give this a try.

**Comment by dhilt** [comment]
@paulflo150 vscroll got fix, and I updated and released ngx-ui-scroll:

[ngx-ui-scroll v2.3.1 is on npm](https://www.npmjs.com/package/ngx-ui-scroll/v/2.3.1)

Please try it, I believe it resolves the problem. If you find anything more, we'll reopen the issue.
