### ISSUE TITLE
Scrolling bug with CSS grid layout

### ISSUE THREAD

**Issue by YannickArmspach** [dhilt/vscroll#37]
Hi, I'am trying to use vscroll with a grid layout. The virtual dom works well but the visibility of the elements is not centered in the scrolling view.

https://stackblitz.com/edit/vscroll-vue-integration-kbdzxp?file=src/App.vue

I think this is the data-padding-forward calculation. I'm trying to equilibrate this by setting the item height to 80px with css rules and setting the itemSize parameters to 20 (my grid has 4 items per row) but I keep the same bug.

An idea ?

**Comment by dhilt** [comment]
@YannickArmspach Is it correct that you are trying to implement floating UI, when there may be uncertain number of items per row? Currently Scroller does not have floating functionality, but there is a workaround when you display group of items in a row (not 1 item per row but some fixed numer of items per row) and set up the process of recalculating the number of elements in a row each time the viewport is resized. This approach is an emulation of css-based floating. There are two demos for Angular, but I believe you can adapt it for Vue:

 - [simple grouping demo](https://stackblitz.com/edit/angular-ngx-ui-scroll-grouping-2) (number of items per row is fixed and don't be changed, just to catch the idea of grouping layout)
 - [float grouping demo](https://stackblitz.com/edit/angular-ngx-ui-scroll-grouping-flex) (layout is changed per each resize event) 

Both demos are taken from https://github.com/dhilt/ngx-ui-scroll/issues/267. I hope this will be helpful and you will be able to apply the approach in the Vue context. Also, it would be great if you share your fixed demo when it is ready, as it may be very useful for others.
